# fly.toml file generated for protohackers-ivo on 2022-10-03T22:53:21+01:00

app = "protohackers-ivo"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  FLY = "true"
  RUST_LOG = "debug"
  RUST_BACKTRACE = 1

[[services]]
  internal_port = 10000
  [[services.ports]]
    port = 10000

[[services]]
  internal_port = 10001
  [[services.ports]]
    port = 10001

[[services]]
  internal_port = 10002
  [[services.ports]]
    port = 10002

[[services]]
  internal_port = 10003
  [[services.ports]]
    port = 10003

[[services]]
  protocol = "udp"
  internal_port = 10004
  [[services.ports]]
    port = 10004

[[services]]
  internal_port = 10005
  [[services.ports]]
    port = 10005

[[services]]
  internal_port = 10006
  [[services.ports]]
    port = 10006
  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

[[services]]
  protocol = "udp"
  internal_port = 10007
  [[services.ports]]
    port = 10007

[[services]]
  internal_port = 10008
    [[services.ports]]
        port = 10008
