# fly.toml file generated for protohackers-ivo on 2022-10-03T22:53:21+01:00

app = "protohackers-ivo"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[[services]]
  internal_port = 10000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 10000

[[services]]
  internal_port = 10001
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 10001
